language: python
python:
- 2.6
- 2.7
- pypy
install:
- pip install "pytest>=2.3.0"
script:
- py.test
notifications:
  irc:
    channels:
    - "irc://ocarina.irc.ozinger.org:8080#hongminhee"
    on_success: change
    on_failure: always
