language: python
addons:
  apt:
    packages:
    - libmagickwand-dev
    - libmagickcore5-extra
    - ghostscript
    - gsfonts
before_install:
- 'export BUCKET_IDX="$(expr "${TRAVIS_JOB_NUMBER#[0-9]*.}" % 6)"'
- export IMAGEATTACH_TEST_S3_NAME="sqla-ia-test${BUCKET_IDX}"
- export IMAGEATTACH_TEST_S3_SANDBOX_NAME="sqla-ia-testx${BUCKET_IDX}"
install:
- pip install tox-travis coveralls
before_script:
- createdb -U postgres -E utf8 -T postgres si_test
- mysql -e "CREATE DATABASE si_test;"
script:
# SQLite
- tox -- --cov sqlalchemy_imageattach --durations=20
# PostgreSQL
- tox -- --cov sqlalchemy_imageattach --durations=20 --database-url='postgresql:///si_test?user=postgres'
# MySQL
- |
  if [[ "$TRAVIS_PYTHON_VERSION" = "pypy" ]]; then
    tox -- --cov sqlalchemy_imageattach --durations=20 --database-url='mysql+pymysql://root@localhost/si_test'
  else
    tox -- --cov sqlalchemy_imageattach --durations=20 --database-url='mysql+mysqlconnector://root@localhost/si_test'
  fi
after_success:
- coveralls
python:
# CHECK If you're going to change the list of supported Python versions
# update tox.ini and setup.py's classifiers as well.
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
