language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
env:
  global:
  - secure: "m2miJTnJPlSo2xFppOenQpzrCwxOyUztMlNdQ3GSrkVnE5g/USsFTfD018Si\nniQDBkt2B8+JJZWo42SdP+8rf75y6piwNRxgmMWyON8s9Jsq5g+QFHKaCwtc\nobEYzrrHkCahZ+lUedGL+8ff9zvYm+IcdKpiLQTET84K1ctrRyE="
  - secure: "qnxIMBzUhRnT6TpEn1CfD6vQltzwppNjdJ2PL9bO12jyETIuwo+ktaJ8r5bc\nKVI8rZW5sdD4sO0qEsz5JJSGh2Ih+Y9YiXg8OzK28noLocXQgv0TItO7sghl\nHPHcwEzfH4PtkS8v+0f82nS74WXAEsNZLi2lhpghH3ODFd8ZYI0="
  - IMAGEATTACH_TEST_S3_NAME=sqla-imageattach-test
  - IMAGEATTACH_TEST_S3_SANDBOX_NAME=sqla-imageattach-test2
  - MYSQL_CONNECTOR_PYTHON_URL='https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.7.tar.gz'
  matrix:
  - DB=sqlite
  - DB=postgresql
  - DB=mysql
before_install:
- export PY=`python -c 'import sys;print("pypy" if hasattr(sys,"pypy_version_info") else "%d.%d" % sys.version_info[:2])'`
install:
- pip install pytest SQLAlchemy-Utils WebOb pytest-capturelog flake8 'pip>=8.1.2' 'setuptools>=23.1.0' pytest-cov coveralls
- if [ "$DB" = "sqlite" ]; then
    export IMAGEATTACH_TEST_DATABASE_URL='sqlite://';
  fi
- if [ "$DB" = "postgresql" ]; then
    export IMAGEATTACH_TEST_DATABASE_URL='postgresql:///si_test?user=postgres';
    if [ "$PY" = "pypy" ]; then
      pip install psycopg2ct;
    else
      pip install psycopg2;
    fi;
  fi
- if [ "$DB" = "mysql" ]; then
    export IMAGEATTACH_TEST_DATABASE_URL='mysql+mysqlconnector://root@localhost/si_test';
    if [ "$PY" = "pypy" ]; then
      pip install PyMySQL;
      export IMAGEATTACH_TEST_DATABASE_URL=${IMAGEATTACH_TEST_DATABASE_URL/mysqlconnector/pymysql};
    else
      pip install --find-links="$MYSQL_CONNECTOR_PYTHON_URL" --allow-all-external mysql-connector-python;
    fi;
  fi
- pip install --pre "SQLAlchemy>=1.1.0b1" -e .
before_script:
- if [ "$DB" = "postgresql" ]; then createdb -U postgres -E utf8 -T postgres si_test; fi
- if [ "$DB" = "mysql" ]; then mysql -e "CREATE DATABASE si_test;"; fi
script:
# SQLAlchemy 1.1
- py.test --cov sqlalchemy_imageattach --durations=20;
# SQLAlchemy 1.0
- pip uninstall --yes SQLAlchemy && pip install "SQLAlchemy>=1.0.0,<1.1.0"
- py.test
# SQLAlchemy 0.9
- pip uninstall --yes SQLAlchemy && pip install "SQLAlchemy>=0.9.0,<1.0.0"
- py.test
# SQLAlchemy 0.8
- pip uninstall --yes SQLAlchemy && pip install "SQLAlchemy>=0.8.0,<0.9.0"
- py.test
# Lint
- flake8
after_success:
- coveralls
