language: python
addons:
  apt:
    packages:
    - libmagickwand-dev
    - libmagickcore5-extra
    - ghostscript
    - gsfonts
cache:
  directories:
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/.tox
before_install:
- 'export BUCKET_IDX="$(expr "${TRAVIS_JOB_NUMBER#[0-9]*.}" % 4)"'
- export IMAGEATTACH_TEST_S3_NAME="si-test${BUCKET_IDX}"  # AWS2Auth
- export IMAGEATTACH_TEST_S3_AWS4AUTH_NAME="si-test${BUCKET_IDX}-v4"
- export IMAGEATTACH_TEST_S3_AWS4AUTH_REGION="us-east-2"
- export IMAGEATTACH_TEST_S3_SANDBOX_NAME="si-testx${BUCKET_IDX}"
install:
- pip install tox-travis coveralls
- tox --notest  # for cache
before_script:
- createdb -U postgres -E utf8 -T postgres si_test
- mysql -e "CREATE DATABASE si_test;"
script:
# SQLite & AWS4Auth
- tox -- -vv --cov sqlalchemy_imageattach --durations=20 --s3-name="$IMAGEATTACH_TEST_S3_AWS4AUTH_NAME" --s3-region="$IMAGEATTACH_TEST_S3_AWS4AUTH_REGION"
# PostgreSQL & AWS2Auth
- tox -- -vv --cov sqlalchemy_imageattach --durations=20 --database-url='postgresql:///si_test?user=postgres'
# MySQL & AWS2Auth
- |
  if [[ "$TRAVIS_PYTHON_VERSION" = "pypy" ]]; then
    tox -- -vv --cov sqlalchemy_imageattach --durations=20 --database-url='mysql+pymysql://root@localhost/si_test'
  else
    tox -- -vv --cov sqlalchemy_imageattach --durations=20 --database-url='mysql+mysqlconnector://root@localhost/si_test'
  fi
after_success:
- coveralls
python:
# CHECK If you're going to change the list of supported Python versions
# update tox.ini and setup.py's classifiers as well.
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
- pypy
