language: python
python:
- 2.6
- 2.7
- pypy
env:
- DB=sqlite IMAGEATTACH_TEST_DATABASE_URL='sqlite://'
- DB=postgresql DRIVER=psycopg2ct IMAGEATTACH_TEST_DATABASE_URL='postgresql:///si_test?user=postgres'
- DB=mysql DRIVER=PyMySQL IMAGEATTACH_TEST_DATABASE_URL='mysql+pymysql://root@localhost/si_test'
install:
- pip install "pytest>=2.3.0" "pytest-cov>=1.6" coveralls $DRIVER -e .
before_script:
- if [ "$DB" = "postgresql" ]; then createdb -U postgres -E utf8 -T postgres si_test; fi
- if [ "$DB" = "mysql" ]; then mysql -e "CREATE DATABASE si_test;"; fi
script:
- py.test --cov sqlalchemy_imageattach --durations=20
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc://ocarina.irc.ozinger.org:8080#hongminhee"
    on_success: change
    on_failure: always
